#!/usr/bin/env node
// Generates the README's input/output reference from the action.yml files, so the two
// cannot drift: `node scripts/reference.mjs --write` rewrites the block between the
// reference markers in README.md; test/static.test.mjs fails when it is stale.
//
// The parser reads only the shape this repo's action.yml files use (two-space input
// keys; description as a plain/quoted scalar or a `>-` block; default; required).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const ACTIONS = [
  ["action.yml", "Wave-RF/cloudflare-preview@v1", "Upload + Deployment + preview comment in one step."],
  ["upload/action.yml", "Wave-RF/cloudflare-preview/upload@v1", "`wrangler versions upload` with retries and a per-PR alias."],
  ["deploy/action.yml", "Wave-RF/cloudflare-preview/deploy@v1", "`wrangler deploy` to production, with an optional Deployment record."],
  ["deployment/action.yml", "Wave-RF/cloudflare-preview/deployment@v1", "A GitHub Deployment and its status; PR-close cleanup."],
  ["preview-comment/action.yml", "Wave-RF/cloudflare-preview/preview-comment@v1", "The sticky preview comment."],
  ["comment/action.yml", "Wave-RF/cloudflare-preview/comment@v1", "A generic sticky comment: any body, any marker."],
];
const WORKFLOW = ".github/workflows/preview.yml";
const START = "<!-- reference:start (generated by scripts/reference.mjs; do not edit by hand) -->";
const END = "<!-- reference:end -->";

const unquote = (v) => {
  const t = v.trim();
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) return t.slice(1, -1);
  return t;
};

function section(lines, name) {
  const i = lines.indexOf(`${name}:`);
  if (i === -1) return [];
  const indent = name.length - name.trimStart().length;
  const out = [];
  for (let j = i + 1; j < lines.length && (lines[j] === "" || lines[j].search(/\S/) > indent); j++) out.push(lines[j]);
  return out;
}

export function parseAction(text, { base = 0 } = {}) {
  const lines = text.split("\n");
  const pad = (n) => " ".repeat(base + n);
  const parse = (block) => {
    const items = [];
    let cur = null;
    for (let i = 0; i < block.length; i++) {
      const line = block[i];
      let m;
      if ((m = new RegExp(`^${pad(2)}([A-Za-z0-9_-]+):\\s*$`).exec(line))) {
        cur = { name: m[1], description: "", default: undefined, required: false };
        items.push(cur);
      } else if (cur && (m = new RegExp(`^${pad(4)}description:\\s*(.*)$`).exec(line))) {
        if (/^[>|]-?$/.test(m[1].trim())) {
          const parts = [];
          while (i + 1 < block.length && block[i + 1].startsWith(pad(6))) parts.push(block[++i].trim());
          cur.description = parts.join(" ");
        } else cur.description = unquote(m[1]);
      } else if (cur && (m = new RegExp(`^${pad(4)}default:\\s*(.*)$`).exec(line))) cur.default = unquote(m[1]);
      else if (cur && (m = new RegExp(`^${pad(4)}required:\\s*(.*)$`).exec(line))) cur.required = m[1].trim() === "true";
    }
    return items;
  };
  return { inputs: parse(section(lines, `${pad(0)}inputs`)), outputs: parse(section(lines, `${pad(0)}outputs`)) };
}

const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (s) => (s === undefined ? "" : s === "" ? '`""`' : `\`${s.replace(/`/g, "")}\``);

export function render() {
  const out = [START, ""];
  for (const [file, uses, summary] of ACTIONS) {
    const { inputs, outputs } = parseAction(readFileSync(join(ROOT, file), "utf8"));
    out.push(`### \`${uses}\``, "", `${summary} Source: [\`${file}\`](${file}).`, "");
    out.push("| Input | Default | Description |", "| --- | --- | --- |");
    for (const i of inputs) out.push(`| \`${i.name}\`${i.required ? " (required)" : ""} | ${cell(code(i.default))} | ${cell(i.description)} |`);
    out.push("", "| Output | Description |", "| --- | --- |");
    for (const o of outputs) out.push(`| \`${o.name}\` | ${cell(o.description)} |`);
    out.push("");
  }
  const wf = parseAction(readFileSync(join(ROOT, WORKFLOW), "utf8"), { base: 4 });
  out.push("### Reusable workflow `.github/workflows/preview.yml`", "", `Called with \`uses: Wave-RF/cloudflare-preview/${WORKFLOW}@v1\`. Source: [\`${WORKFLOW}\`](${WORKFLOW}). Secrets: \`CLOUDFLARE_API_TOKEN\`, \`CLOUDFLARE_ACCOUNT_ID\` (both optional; empty → previews skip with a warning).`, "");
  out.push("| Input | Default | Description |", "| --- | --- | --- |");
  for (const i of wf.inputs) out.push(`| \`${i.name}\`${i.required ? " (required)" : ""} | ${cell(code(i.default))} | ${cell(i.description)} |`);
  out.push("", "| Output | Description |", "| --- | --- |");
  for (const o of wf.outputs) out.push(`| \`${o.name}\` | ${cell(o.description)} |`);
  out.push("", END);
  return out.join("\n");
}

export function replaceBlock(readme, block) {
  const a = readme.indexOf(START);
  const b = readme.indexOf(END);
  if (a === -1 || b === -1) throw new Error("README.md has no reference markers");
  return readme.slice(0, a) + block + readme.slice(b + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const path = join(ROOT, "README.md");
  const next = replaceBlock(readFileSync(path, "utf8"), render());
  if (process.argv.includes("--write")) writeFileSync(path, next);
  else process.stdout.write(`${render()}\n`);
}
